@include('layouts.header')
@include('layouts.navbar')
<div class="row">
    @include('layouts.sidebar')
    <div class="col-md-9">
        @if (session('success'))
            <div class="alert alert-success alert-dismissible">
            {{ session('success') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger alert-dismissible">
            {{ session('error') }}
            </div>
        @endif

        {{-- display all date from the return view('reports.previous', compact('reports')); reportcontroller --}}
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Report ID</th>
                        <th>Report Type</th>
                        <th>Start Date</th>
                        <th>End Date</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                        <tr>
                            <td>{{ $report->id }}</td>
                            <td>{{ $report->type }}</td>
                            <td>{{ $report->start }}</td>
                            <td>{{ $report->end }}</td>
                            <td>{{ ucwords($report->user->first_name) }} {{ ucwords($report->user->last_name) }}</td>
                            <td>{{ $report->created_at }}</td>
                            <td>
                                {{-- <a href="{{ route('report.show', $report->id) }}" class="btn btn-primary btn-sm">View</a> --}}

                                <a href="{{ route('report.download', $report->id) }}" class="btn btn-success btn-sm">Download</a>
                                {{-- <a href="{{ route('report.destroy', $report->id) }}" class="btn btn-danger btn-sm">Delete</a> --}}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            {{ $reports->links('pagination::bootstrap-4') }}
    </div>
</div>

@include('layouts.footer')
@include('reports.cashonhand')

